db.url=jdbc:postgresql://localhost:5432/bankdb
db.user=postgres
db.password=12345678

# Ensure dummy values for mail if we just want to stub it
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.user=narayananhari399@gmail.com
mail.password=qfrz ussc ddtr arzy

